# top
seed: 0
pilot: false
local_data_folder: ./data
wandb_project_name: draftrec
exp_name: test
dataset_type: lol
model_type: nn
# dataloader
train_dataloader_type: match
val_dataloader_type: match
test_dataloader_type: match
train_batch_size: 512
val_batch_size: 512
test_batch_size: 512
max_seq_len: 1
num_special_tokens: 4
num_turns: 10
num_champions: null
num_roles: null
num_teams: null
num_outcomes: null
num_stats: null
num_users: null
num_negatives: 128
window_size: 100
# trainer
trainer_type: match
device: cuda
use_parallel: false
num_workers: 8  # larger number of workers induce higher i/o bottleneck
# optimizer
optimizer: adam
lr: 0.001
weight_decay: 0.00001
momentum: null
lmbda: 0
clip_grad_norm: 5.0
dropout: 0.1
# epochs
num_epochs: 10
# evaluation
metric_ks:
- 1
- 5
- 10
- 20
best_metric: ACC
# model
model_init_seed: 0
hidden_units: 64
num_blocks: null
head_type: null
num_heads: null
num_hidden_layers: null
min_prob: null